// Generated by CoffeeScript 1.7.1
var Model, racer;

racer = require('racer');

Model = racer.Model;

module.exports = function(app, options) {
  var Flash;
  options || (options = {});
  return Flash = (function() {
    var middleware, originalRouter;

    function Flash() {}

    Flash.prototype.view = __dirname;

    app.on('render', function(app) {
      var flashq, model, msg, type, _i, _len, _ref;
      model = app.model;
      flashq = model.get('_flash.flashq') || {};
      if (options.useToast && model.toast) {
        if (flashq) {
          for (type in flashq) {
            _ref = flashq[type];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              msg = _ref[_i];
              if (options.useToast && model.toast) {
                model.toast(type, msg);
              }
            }
          }
        }
      } else {
        model.root.set('_page.flash', flashq);
      }
      return model.del('_flash.flashq');
    });

    Model.prototype.flash = function(type, msg, useToast) {
      var _ref;
      if (type && msg) {
        if (((_ref = this.req) != null ? _ref.flash : void 0) && !useToast) {
          return this.req.flash(type, msg);
        } else {
          return this.root.push("_flash.flashq." + type, msg);
        }
      }

      /*
      			else if type
      				if @req?.flash
      					@req.flash type
      				else
      					res = @root.get "_flash.flashq.#{type}"
      					@root.del "_flash.flashq.#{type}"
      					res
      			else
      				if @req?.flash
      					@req.flash
      				else
      					all = @root.get "_flash.flashq"
      					@root.del "_flash.flashq"
      					all
       */
    };

    originalRouter = app.router;

    middleware = function(req, res, next) {
      var model, msg, msgs, obj, type, _i, _len, _ref;
      if (req.flash) {
        model = req.getModel();
        msgs = req.flash();
        for (type in msgs) {
          _ref = msgs[type];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            msg = _ref[_i];
            if (typeof msg === 'string') {
              model.push("_flash.flashq." + type, msg);
            } else {
              for (obj in msg) {
                model.set("_flash.flashq." + type + "." + obj, msg[obj]);
              }
            }
          }
        }
      }
      return (originalRouter())(req, res, next);
    };

    app.router = function() {
      return middleware;
    };

    return Flash;

  })();
};
