// Generated by CoffeeScript 1.5.0
var flash;

flash = module.exports;

flash.init = function(app) {
  var middleware, originalRouter, show;
  show = function() {
    var flashq, flashq2, model, msg, type, _i, _len, _ref;
    model = this.view.model;
    flashq = model.get('_flashq') || {};
    flashq2 = model.get('_flashq2') || {};
    for (type in flashq2) {
      flashq[type] || (flashq[type] = []);
      _ref = flashq2[type];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        msg = _ref[_i];
        flashq[type].push(msg);
      }
    }
    model.set('_flash', flashq);
    model.del('_flashq');
    return model.del('_flashq2');
  };
  app.on('render', show);
  app.flash = function(type, msg) {
    return this.view.model.push("_flashq." + type, msg);
  };
  originalRouter = app.router;
  middleware = function(req, res, next) {
    var model;
    model = req.getModel();
    if (req.flash) {
      model.set('_flashq2', req.flash());
    }
    return (originalRouter())(req, res, next);
  };
  app.router = function() {
    return middleware;
  };
  return app;
};
